#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 1.0.{build}.0
install: 
  - git clone https://github.com/Indhukrishna/AppveyorTest
  - ps: $pwd
  - cd Tests

#---------------------------------# 
#      build configuration        # 
#---------------------------------# 

build: false

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 

test_script:
    - ps: |
        $pwd
        $res = & .\CreateObjectTest.ps1
        $res
        "<a></a>" > TestResults.xml
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResults.xml))
        Push-AppveyorArtifact (Resolve-Path .\CreateObjectTest.ps1)         
        