#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 1.0.{build}.0
install: 
  - cinst -y pester
  - git clone https://github.com/Indhukrishna/AppveyorTest
  - ps: Push-Location
  - cd Tests
  - ps: Pop-Location

#---------------------------------# 
#      build configuration        # 
#---------------------------------# 

build: false

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 

test_script:
    - ps: |
        $testResultsFile = ".\TestsResults.xml"
        $res = & .\CreateObjectTest.ps1
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        Push-AppveyorArtifact (Resolve-Path $testResultsFile)
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }   
        